package sudoku.app.learn

import sudoku.app.model.*
import sudoku.app.model.HighlightRole.*

/**
 * Strategy encyclopedia content — theory, spotting tips, and board examples for
 * every SolutionType (except BRUTE_FORCE).
 *
 * Solver-backed techniques have pre-baked examples generated by GenerateExamplesTask.
 * A few rare types (Locked Pair/Triple, Jellyfish) may have null examples — these get
 * on-demand generation via the "New example" button. Non-solver techniques keep
 * hand-crafted examples.
 *
 * Content derived from HoDoKu (GPL) solving documentation.
 */

/** All strategy entries indexed by SolutionType. */
val strategyEntries: Map<SolutionType, StrategyEntry> by lazy {
    allEntries.associateBy { it.type }
}

/** Ordered list of all entries (follows SolutionType declaration order). */
val allEntries: List<StrategyEntry> by lazy { buildEntries() }

// Helper: create bitmask for a set of candidate digits
private fun mask(vararg digits: Int): Int {
    var m = 0
    for (d in digits) m = m or (1 shl (d - 1))
    return m
}

// Helper: cell index from row,col (0-based)
private fun cell(
    row: Int,
    col: Int,
): Int = row * 9 + col

/**
 * Build a full candidateMasks array from a puzzle string plus a sparse
 * map of cell->mask overrides. Any empty cell (0) not in the overrides
 * gets its candidates computed from the puzzle automatically.
 */
private fun fullBoard(
    puzzle: String,
    overrides: Map<Int, Int> = emptyMap(),
): IntArray {
    val values =
        IntArray(81) { i ->
            val ch = puzzle[i]
            if (ch in '1'..'9') ch - '0' else 0
        }
    return IntArray(81) { i ->
        if (values[i] != 0) {
            0
        } else {
            overrides[i] ?: computeCandidateMask(values, i)
        }
    }
}

private fun computeCandidateMask(
    values: IntArray,
    index: Int,
): Int {
    val row = index / 9
    val col = index % 9
    val boxRow = (row / 3) * 3
    val boxCol = (col / 3) * 3
    var m = 0x1FF
    for (c in 0..8) {
        val d = values[row * 9 + c]
        if (d != 0) m = m and (1 shl (d - 1)).inv()
    }
    for (r in 0..8) {
        val d = values[r * 9 + col]
        if (d != 0) m = m and (1 shl (d - 1)).inv()
    }
    for (r in boxRow until boxRow + 3) {
        for (c in boxCol until boxCol + 3) {
            val d = values[r * 9 + c]
            if (d != 0) m = m and (1 shl (d - 1)).inv()
        }
    }
    return m
}

@Suppress("LongMethod")
private fun buildEntries(): List<StrategyEntry> =
    listOf(
        // ── Singles ──────────────────────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.FULL_HOUSE,
            theory =
                "A Full House occurs when a row, column, or box has exactly one empty cell remaining. " +
                    "Since all other eight digits are placed, the missing digit is forced into the last cell.\n\n" +
                    "This is the simplest possible solving technique — no candidate analysis is needed. " +
                    "Just count the placed digits in the unit and fill in the missing one.",
            howToSpot =
                "• Scan each row, column, and box for units with only one empty cell.\n" +
                    "• Count placed digits: if eight are present, the ninth is determined.\n" +
                    "• These are most common in the late stages of a solve.",
            example =
                BoardExample(
                    puzzle = "..9..........6..155..4.8...61.....8.9846.2531.3.....42...3.5..612..8..........4..",
                    candidateMasks =
                        intArrayOf(
                            206, 104, 0, 83, 87, 69, 230, 98, 204,
                            206, 72, 198, 322, 0, 324, 454, 0, 0,
                            0, 96, 103, 0, 327, 0, 358, 354, 324,
                            0, 0, 82, 336, 348, 332, 320, 0, 320,
                            0, 0, 0, 0, 64, 0, 0, 0, 0,
                            64, 0, 80, 465, 337, 321, 352, 0, 0,
                            200, 328, 192, 0, 331, 0, 451, 322, 0,
                            0, 0, 116, 320, 0, 360, 324, 336, 324,
                            196, 368, 244, 323, 323, 353, 0, 338, 452
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(40, 7, HighlightRole.DEFINING),
                        ),
                ),
            relatedTypes = listOf(SolutionType.NAKED_SINGLE, SolutionType.HIDDEN_SINGLE),
            keywords = listOf("last digit", "single empty", "forced"),
        ),
        StrategyEntry(
            type = SolutionType.NAKED_SINGLE,
            theory =
                "A Naked Single is a cell that has only one candidate remaining after all peer eliminations. " +
                    "Every other digit 1–9 appears in the cell's row, column, or box, leaving exactly one possibility.\n\n" +
                    "This is the most fundamental technique after Full House and is the backbone of easy puzzles. " +
                    "Whenever you place a digit, check if the affected peers now have naked singles.",
            howToSpot =
                "• Look for cells with only one pencil mark.\n" +
                    "• After placing a digit, re-scan the 20 peer cells.\n" +
                    "• In candidate mode, naked singles stand out visually as cells with a single small digit.",
            example =
                BoardExample(
                    puzzle = ".5.1....7....2.....83.54...8.7..54...32...86...59..2.1...47.15.....1....1....6.9.",
                    candidateMasks =
                        intArrayOf(
                            298, 0, 296, 0, 420, 388, 292, 142, 0,
                            360, 361, 297, 228, 0, 452, 308, 141, 444,
                            354, 0, 0, 96, 0, 0, 288, 3, 290,
                            0, 289, 0, 38, 36, 0, 0, 4, 260,
                            264, 0, 0, 64, 8, 65, 0, 0, 272,
                            40, 40, 0, 0, 172, 196, 0, 68, 0,
                            294, 290, 416, 0, 0, 390, 0, 0, 166,
                            382, 362, 424, 150, 0, 390, 100, 206, 174,
                            0, 74, 136, 150, 132, 0, 68, 0, 142
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(34, 3, HighlightRole.DEFINING),
                        ),
                ),
            relatedTypes = listOf(SolutionType.FULL_HOUSE, SolutionType.HIDDEN_SINGLE),
            keywords = listOf("sole candidate", "one candidate", "singles"),
        ),
        StrategyEntry(
            type = SolutionType.HIDDEN_SINGLE,
            theory =
                "A Hidden Single occurs when a digit can only go in one cell within a row, column, or box, " +
                    "even though that cell may have other candidates too. The digit is 'hidden' among other possibilities.\n\n" +
                    "For each unit (row/col/box), check where each digit 1–9 can be placed. " +
                    "If a digit has only one possible cell in a unit, it must go there regardless of other candidates in that cell.",
            howToSpot =
                "• For each unit, count the possible positions for each digit.\n" +
                    "• A digit with exactly one possible position in any unit is a hidden single.\n" +
                    "• Use candidate filtering to highlight a single digit and look for isolated occurrences in a unit.",
            example =
                BoardExample(
                    puzzle = "6..19.54..97....2....5..6..2.98.........1.........49.8..4..3....1....27..82.61..9",
                    candidateMasks =
                        intArrayOf(
                            0, 6, 132, 0, 0, 194, 0, 0, 68,
                            157, 0, 0, 44, 140, 160, 133, 0, 5,
                            141, 14, 133, 0, 206, 194, 0, 389, 69,
                            0, 124, 0, 0, 84, 112, 77, 53, 125,
                            220, 124, 180, 358, 0, 370, 76, 52, 126,
                            85, 116, 53, 102, 86, 0, 0, 53, 0,
                            336, 112, 0, 322, 210, 0, 129, 177, 49,
                            276, 0, 52, 264, 152, 400, 0, 0, 60,
                            84, 0, 0, 72, 0, 0, 12, 20, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(9, 5, HighlightRole.DEFINING),
                        ),
                ),
            relatedTypes = listOf(SolutionType.FULL_HOUSE, SolutionType.NAKED_SINGLE),
            keywords = listOf("unique position", "sole position", "hidden"),
        ),
        // ── Locked Candidates ───────────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.LOCKED_CANDIDATES_1,
            theory =
                "Pointing occurs when all candidates for a digit within a box are confined to a single row or column. " +
                    "Since one of those cells must contain the digit, it can be eliminated from all other cells in that row or column outside the box.\n\n" +
                    "Think of it this way: the box 'claims' that digit for that row/column, so the rest of the row/column can't have it.",
            howToSpot =
                "• In each box, check if a candidate digit appears only in one row or one column.\n" +
                    "• If so, that digit can be eliminated from the same row/column in other boxes.\n" +
                    "• Filter candidates by digit — look for box-aligned patterns.",
            example =
                BoardExample(
                    puzzle = "3.6...915..96.53.....391..6.7381265.862....3...5.6382.2...36.9..371.9.6.691...4.3",
                    candidateMasks =
                        intArrayOf(
                            0, 138, 0, 74, 202, 200, 0, 0, 0,
                            73, 139, 0, 0, 202, 0, 0, 200, 202,
                            88, 154, 136, 0, 0, 0, 66, 200, 0,
                            264, 0, 0, 0, 0, 0, 0, 0, 264,
                            0, 0, 0, 344, 88, 72, 65, 0, 329,
                            265, 9, 0, 328, 0, 0, 0, 0, 329,
                            0, 152, 136, 88, 0, 0, 81, 0, 193,
                            24, 0, 0, 0, 154, 0, 18, 0, 130,
                            0, 0, 0, 82, 210, 192, 0, 192, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(45, 1, HighlightRole.DEFINING),
                            CandidateHighlight(46, 1, HighlightRole.DEFINING),
                            CandidateHighlight(53, 1, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.LOCKED_CANDIDATES_2, SolutionType.LOCKED_PAIR),
            keywords = listOf("pointing", "box-line", "intersection"),
        ),
        StrategyEntry(
            type = SolutionType.LOCKED_CANDIDATES_2,
            theory =
                "Claiming (also called Box/Line Reduction) is the reverse of Pointing. When all candidates for a " +
                    "digit in a row or column fall within a single box, that digit can be eliminated from other cells in that box.\n\n" +
                    "The row/column 'claims' the digit must be in that intersection, so the rest of the box can't have it.",
            howToSpot =
                "• In each row/column, check if a candidate digit appears only within one box.\n" +
                    "• If so, eliminate that digit from other cells in that box.\n" +
                    "• Often found when a row or column has few remaining cells for a digit.",
            example =
                BoardExample(
                    puzzle = ".8..91...9...4813..4.3268...94287..3...639...6..4159..4671532...29874..1...962.4.",
                    candidateMasks =
                        intArrayOf(
                            86, 0, 54, 80, 0, 0, 120, 114, 122,
                            0, 80, 50, 80, 0, 0, 0, 0, 114,
                            81, 0, 17, 0, 0, 0, 0, 336, 336,
                            17, 0, 0, 0, 0, 0, 48, 49, 0,
                            211, 81, 147, 0, 0, 0, 88, 211, 218,
                            0, 68, 134, 0, 0, 0, 0, 194, 194,
                            0, 0, 0, 0, 0, 0, 0, 384, 384,
                            20, 0, 0, 0, 0, 0, 52, 48, 0,
                            149, 21, 149, 0, 0, 0, 84, 0, 80
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(8, 6, HighlightRole.DEFINING),
                            CandidateHighlight(17, 6, HighlightRole.DEFINING),
                            CandidateHighlight(6, 6, HighlightRole.ELIMINATION),
                            CandidateHighlight(7, 6, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.LOCKED_CANDIDATES_1, SolutionType.LOCKED_PAIR),
            keywords = listOf("claiming", "box-line reduction", "intersection"),
        ),
        StrategyEntry(
            type = SolutionType.LOCKED_PAIR,
            theory =
                "A Locked Pair is a Naked Pair that is confined to the intersection of a box and a row/column. " +
                    "Because the two digits are locked in that intersection, they can be eliminated from the rest of " +
                    "both the box and the line simultaneously.\n\n" +
                    "This combines the logic of Naked Pairs with Locked Candidates for stronger eliminations.",
            howToSpot =
                "• Find a Naked Pair (two cells with the same two candidates) in a box.\n" +
                    "• Check if both cells share the same row or column.\n" +
                    "• If so, eliminate those digits from both the rest of the row/column AND the rest of the box.",
            example =
                BoardExample(
                    puzzle = ".4.3.6.....381..646....43.2.3...817...8...43..915.3.2.3.92....7.5..37......6...53",
                    candidateMasks =
                        intArrayOf(
                            467, 0, 82, 0, 338, 0, 464, 385, 129,
                            338, 66, 0, 0, 0, 274, 336, 0, 0,
                            0, 193, 80, 320, 336, 0, 0, 385, 0,
                            26, 0, 58, 264, 298, 0, 0, 0, 304,
                            82, 98, 0, 321, 354, 259, 0, 0, 304,
                            72, 0, 0, 0, 104, 0, 160, 0, 160,
                            0, 161, 0, 0, 152, 17, 160, 137, 0,
                            139, 0, 42, 265, 0, 0, 418, 393, 161,
                            203, 195, 74, 0, 392, 257, 386, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(51, 6, HighlightRole.DEFINING),
                            CandidateHighlight(51, 8, HighlightRole.DEFINING),
                            CandidateHighlight(53, 6, HighlightRole.DEFINING),
                            CandidateHighlight(53, 8, HighlightRole.DEFINING),
                            CandidateHighlight(35, 6, HighlightRole.ELIMINATION),
                            CandidateHighlight(44, 6, HighlightRole.ELIMINATION),
                            CandidateHighlight(49, 6, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.LOCKED_CANDIDATES_1, SolutionType.NAKED_PAIR),
            keywords = listOf("locked pair", "box-line pair"),
        ),
        StrategyEntry(
            type = SolutionType.LOCKED_TRIPLE,
            theory =
                "A Locked Triple is a Naked Triple confined to the intersection of a box and a line. " +
                    "Three cells in the intersection share three candidates among them, allowing eliminations " +
                    "from both the remaining box cells and the remaining line cells.\n\n" +
                    "This is rarer than Locked Pairs but follows the same principle with three candidates.",
            howToSpot =
                "• Find three cells in a box-line intersection whose combined candidates total exactly three digits.\n" +
                    "• Not all three candidates need to appear in every cell.\n" +
                    "• Eliminate those three digits from the rest of both the box and the line.",
            example =
                BoardExample(
                    puzzle = "....83...5.....18.84...1..6..16...979.......173...94..3..9..258..2.....9...72....",
                    candidateMasks =
                        intArrayOf(
                            35, 355, 352, 26, 0, 0, 336, 74, 26,
                            0, 322, 324, 10, 360, 106, 0, 0, 14,
                            0, 0, 324, 18, 336, 0, 340, 70, 0,
                            10, 146, 0, 0, 28, 154, 148, 0, 0,
                            0, 178, 184, 158, 92, 218, 180, 38, 0,
                            0, 0, 176, 147, 17, 0, 0, 34, 18,
                            0, 97, 104, 0, 41, 40, 0, 0, 0,
                            41, 177, 0, 157, 61, 184, 96, 105, 0,
                            41, 433, 440, 0, 0, 184, 36, 45, 12
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(3, 2, HighlightRole.DEFINING),
                            CandidateHighlight(3, 4, HighlightRole.DEFINING),
                            CandidateHighlight(3, 5, HighlightRole.DEFINING),
                            CandidateHighlight(12, 2, HighlightRole.DEFINING),
                            CandidateHighlight(12, 4, HighlightRole.DEFINING),
                            CandidateHighlight(21, 2, HighlightRole.DEFINING),
                            CandidateHighlight(21, 5, HighlightRole.DEFINING),
                            CandidateHighlight(13, 4, HighlightRole.ELIMINATION),
                            CandidateHighlight(14, 2, HighlightRole.ELIMINATION),
                            CandidateHighlight(14, 4, HighlightRole.ELIMINATION),
                            CandidateHighlight(22, 5, HighlightRole.ELIMINATION),
                            CandidateHighlight(39, 2, HighlightRole.ELIMINATION),
                            CandidateHighlight(39, 4, HighlightRole.ELIMINATION),
                            CandidateHighlight(39, 5, HighlightRole.ELIMINATION),
                            CandidateHighlight(48, 2, HighlightRole.ELIMINATION),
                            CandidateHighlight(48, 5, HighlightRole.ELIMINATION),
                            CandidateHighlight(66, 4, HighlightRole.ELIMINATION),
                            CandidateHighlight(66, 5, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.LOCKED_PAIR, SolutionType.NAKED_TRIPLE),
            keywords = listOf("locked triple", "box-line triple"),
        ),
        // ── Subsets ──────────────────────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.NAKED_PAIR,
            theory =
                "A Naked Pair occurs when two cells in the same unit (row, column, or box) contain exactly the " +
                    "same two candidates and nothing else. Since those two digits must occupy those two cells, " +
                    "they can be eliminated from all other cells in the unit.\n\n" +
                    "This is the simplest subset technique and one of the most commonly used strategies in intermediate puzzles.",
            howToSpot =
                "• Look for two cells in a unit each containing exactly two candidates.\n" +
                    "• If both cells have the identical pair, it's a Naked Pair.\n" +
                    "• Eliminate both digits from all other cells in that unit.",
            example =
                BoardExample(
                    puzzle = ".346...598....46..6....14..5..369247479.1.3653624579....6.....4.4.1....625.74689.",
                    candidateMasks =
                        intArrayOf(
                            65, 0, 0, 0, 130, 130, 65, 0, 0,
                            0, 259, 81, 272, 68, 0, 0, 69, 7,
                            0, 258, 80, 272, 68, 0, 0, 196, 134,
                            0, 129, 129, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 130, 0, 130, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 129, 129,
                            321, 129, 0, 130, 386, 150, 81, 71, 0,
                            320, 0, 196, 0, 386, 150, 80, 70, 0,
                            0, 0, 5, 0, 0, 0, 0, 0, 5
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(28, 1, HighlightRole.DEFINING),
                            CandidateHighlight(28, 8, HighlightRole.DEFINING),
                            CandidateHighlight(55, 1, HighlightRole.DEFINING),
                            CandidateHighlight(55, 8, HighlightRole.DEFINING),
                            CandidateHighlight(10, 1, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.HIDDEN_PAIR, SolutionType.NAKED_TRIPLE),
            keywords = listOf("pair", "subset", "naked subset"),
        ),
        StrategyEntry(
            type = SolutionType.NAKED_TRIPLE,
            theory =
                "A Naked Triple occurs when three cells in a unit collectively contain exactly three candidates. " +
                    "Not every cell needs all three digits — the union of their candidates must equal exactly three.\n\n" +
                    "For example, cells with {1,3}, {1,7}, and {3,7} form a naked triple on digits 1,3,7. " +
                    "Those three digits can be eliminated from all other cells in the unit.",
            howToSpot =
                "• Find three cells in a unit whose combined candidates total exactly three digits.\n" +
                    "• Each cell has 2 or 3 candidates, all drawn from the same three-digit set.\n" +
                    "• Eliminate those three digits from the remaining cells in the unit.",
            example =
                BoardExample(
                    puzzle = "....5....3271...95.85.3......86139....14276....25987....9.4136.2.39.51.781.37.5.9",
                    candidateMasks =
                        intArrayOf(
                            297, 296, 40, 194, 0, 266, 138, 69, 37,
                            0, 0, 0, 0, 160, 40, 136, 0, 0,
                            297, 0, 0, 66, 0, 266, 10, 65, 33,
                            88, 88, 0, 0, 0, 0, 0, 18, 10,
                            272, 276, 0, 0, 0, 0, 0, 148, 132,
                            40, 44, 0, 0, 0, 0, 0, 5, 13,
                            80, 80, 0, 130, 0, 0, 0, 0, 130,
                            0, 40, 0, 0, 160, 0, 0, 136, 0,
                            0, 0, 40, 0, 0, 34, 0, 10, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(7, 1, HighlightRole.DEFINING),
                            CandidateHighlight(7, 3, HighlightRole.DEFINING),
                            CandidateHighlight(7, 7, HighlightRole.DEFINING),
                            CandidateHighlight(25, 1, HighlightRole.DEFINING),
                            CandidateHighlight(25, 7, HighlightRole.DEFINING),
                            CandidateHighlight(52, 1, HighlightRole.DEFINING),
                            CandidateHighlight(52, 3, HighlightRole.DEFINING),
                            CandidateHighlight(43, 3, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.NAKED_PAIR, SolutionType.NAKED_QUADRUPLE, SolutionType.HIDDEN_TRIPLE),
            keywords = listOf("triple", "naked subset", "three candidates"),
        ),
        StrategyEntry(
            type = SolutionType.NAKED_QUADRUPLE,
            theory =
                "A Naked Quadruple extends the naked subset concept to four cells containing exactly four candidates. " +
                    "The four digits are locked into those four cells, so they can be eliminated from all other cells in the unit.\n\n" +
                    "While conceptually simple, quads are harder to spot visually because each cell may contain 2, 3, or 4 of the four digits.",
            howToSpot =
                "• Find four cells in a unit whose combined candidates total exactly four digits.\n" +
                    "• Often easier to find by looking for the complementary hidden quad instead.\n" +
                    "• Eliminate those four digits from remaining cells in the unit.",
            example =
                BoardExample(
                    puzzle = "4.5.6.8....2..71.41.78..9..7.3..62..5.6...7.9..47..3.63416.25..6785..4..259.7.6.3",
                    candidateMasks =
                        intArrayOf(
                            0, 260, 0, 263, 0, 261, 0, 70, 66,
                            384, 420, 0, 260, 276, 0, 0, 52, 0,
                            0, 36, 0, 0, 30, 28, 0, 54, 18,
                            0, 385, 0, 265, 409, 0, 0, 153, 145,
                            0, 131, 0, 15, 143, 141, 0, 137, 0,
                            384, 387, 0, 0, 403, 401, 0, 145, 0,
                            0, 0, 0, 0, 384, 0, 0, 448, 192,
                            0, 0, 0, 0, 261, 261, 0, 259, 3,
                            0, 0, 0, 9, 0, 137, 0, 129, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(34, 1, HighlightRole.DEFINING),
                            CandidateHighlight(34, 4, HighlightRole.DEFINING),
                            CandidateHighlight(34, 5, HighlightRole.DEFINING),
                            CandidateHighlight(34, 8, HighlightRole.DEFINING),
                            CandidateHighlight(43, 1, HighlightRole.DEFINING),
                            CandidateHighlight(43, 4, HighlightRole.DEFINING),
                            CandidateHighlight(43, 8, HighlightRole.DEFINING),
                            CandidateHighlight(52, 1, HighlightRole.DEFINING),
                            CandidateHighlight(52, 5, HighlightRole.DEFINING),
                            CandidateHighlight(52, 8, HighlightRole.DEFINING),
                            CandidateHighlight(79, 1, HighlightRole.DEFINING),
                            CandidateHighlight(79, 8, HighlightRole.DEFINING),
                            CandidateHighlight(16, 5, HighlightRole.ELIMINATION),
                            CandidateHighlight(25, 5, HighlightRole.ELIMINATION),
                            CandidateHighlight(61, 8, HighlightRole.ELIMINATION),
                            CandidateHighlight(70, 1, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.NAKED_TRIPLE, SolutionType.HIDDEN_QUADRUPLE),
            keywords = listOf("quad", "quadruple", "naked subset", "four candidates"),
        ),
        StrategyEntry(
            type = SolutionType.HIDDEN_PAIR,
            theory =
                "A Hidden Pair occurs when two candidates appear in exactly two cells within a unit, " +
                    "even though those cells may contain other candidates. Since those two digits must go in those " +
                    "two cells, all other candidates can be eliminated from them.\n\n" +
                    "Hidden Pairs are the 'complement' of Naked Pairs: instead of cells defining the pattern, " +
                    "the digits define it. In a unit of 9 cells, a hidden pair of size 2 implies a naked subset of size 7.",
            howToSpot =
                "• For each unit, check which cells contain each digit.\n" +
                    "• If two digits appear in exactly the same two cells, it's a hidden pair.\n" +
                    "• Remove all other candidates from those two cells.",
            example =
                BoardExample(
                    puzzle = "2....83...397...4.....9.7..5.....634...426...641...9.2..5.1.....1...7865...5....3",
                    candidateMasks =
                        intArrayOf(
                            0, 112, 104, 33, 56, 0, 0, 273, 289,
                            129, 0, 0, 0, 48, 19, 19, 0, 161,
                            137, 176, 168, 39, 0, 31, 0, 147, 161,
                            0, 194, 194, 385, 192, 257, 0, 0, 0,
                            452, 448, 196, 0, 0, 0, 17, 209, 193,
                            0, 0, 0, 132, 212, 20, 0, 192, 0,
                            460, 482, 0, 422, 0, 270, 10, 322, 320,
                            268, 0, 14, 262, 12, 0, 0, 0, 0,
                            456, 482, 234, 0, 168, 266, 11, 323, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(30, 1, HighlightRole.DEFINING),
                            CandidateHighlight(30, 9, HighlightRole.DEFINING),
                            CandidateHighlight(32, 1, HighlightRole.DEFINING),
                            CandidateHighlight(32, 9, HighlightRole.DEFINING),
                            CandidateHighlight(30, 8, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.NAKED_PAIR, SolutionType.HIDDEN_TRIPLE),
            keywords = listOf("hidden pair", "hidden subset", "complement"),
        ),
        StrategyEntry(
            type = SolutionType.HIDDEN_TRIPLE,
            theory =
                "A Hidden Triple occurs when three candidates are confined to exactly three cells in a unit. " +
                    "Other candidates in those cells can be eliminated, leaving only the triple's digits.\n\n" +
                    "Like Hidden Pairs, hidden triples are harder to spot than their naked counterparts because " +
                    "the pattern cells contain 'extra' candidates that obscure the triple.",
            howToSpot =
                "• For each unit, map each digit to its possible cells.\n" +
                    "• If three digits share exactly the same three cells, it's a hidden triple.\n" +
                    "• Remove all non-triple candidates from those three cells.",
            example =
                BoardExample(
                    puzzle = ".9.2.....28694.....75.8..29.1.8...755...9...884.5...9.73..591...5.7289.3.....3.5.",
                    candidateMasks =
                        intArrayOf(
                            13, 0, 13, 0, 101, 113, 248, 169, 105,
                            0, 0, 0, 0, 0, 81, 84, 5, 65,
                            13, 0, 0, 37, 0, 33, 40, 0, 0,
                            292, 0, 262, 0, 36, 42, 46, 0, 0,
                            0, 34, 70, 37, 0, 107, 46, 45, 0,
                            0, 0, 70, 0, 101, 99, 38, 0, 35,
                            0, 0, 138, 40, 0, 0, 0, 168, 42,
                            41, 0, 9, 0, 0, 0, 0, 40, 0,
                            296, 34, 394, 41, 33, 0, 234, 0, 106
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(6, 5, HighlightRole.DEFINING),
                            CandidateHighlight(6, 7, HighlightRole.DEFINING),
                            CandidateHighlight(6, 8, HighlightRole.DEFINING),
                            CandidateHighlight(15, 5, HighlightRole.DEFINING),
                            CandidateHighlight(15, 7, HighlightRole.DEFINING),
                            CandidateHighlight(78, 7, HighlightRole.DEFINING),
                            CandidateHighlight(78, 8, HighlightRole.DEFINING),
                            CandidateHighlight(6, 4, HighlightRole.ELIMINATION),
                            CandidateHighlight(6, 6, HighlightRole.ELIMINATION),
                            CandidateHighlight(15, 3, HighlightRole.ELIMINATION),
                            CandidateHighlight(78, 2, HighlightRole.ELIMINATION),
                            CandidateHighlight(78, 4, HighlightRole.ELIMINATION),
                            CandidateHighlight(78, 6, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.HIDDEN_PAIR, SolutionType.HIDDEN_QUADRUPLE, SolutionType.NAKED_TRIPLE),
            keywords = listOf("hidden triple", "hidden subset"),
        ),
        StrategyEntry(
            type = SolutionType.HIDDEN_QUADRUPLE,
            theory =
                "A Hidden Quadruple occurs when four candidates are confined to exactly four cells in a unit. " +
                    "All other candidates can be eliminated from those four cells.\n\n" +
                    "Hidden quads are extremely rare in practice because they imply a naked quintuple in the remaining " +
                    "five cells, which is usually easier to spot. They are included for completeness.",
            howToSpot =
                "• Map each digit to its possible cells in the unit.\n" +
                    "• If four digits share exactly four cells, it's a hidden quad.\n" +
                    "• Usually easier to find the complementary naked subset instead.",
            example =
                BoardExample(
                    puzzle = ".9..35271213497685.5.1.2943.2.94..6...........6..58.....5..6194689314752142579836",
                    candidateMasks =
                        intArrayOf(
                            136, 0, 168, 160, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            192, 0, 224, 0, 160, 0, 0, 0, 0,
                            212, 0, 193, 0, 0, 5, 20, 0, 192,
                            476, 68, 201, 98, 34, 5, 28, 3, 448,
                            332, 0, 73, 66, 0, 0, 12, 3, 320,
                            68, 68, 0, 130, 130, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(36, 4, HighlightRole.DEFINING),
                            CandidateHighlight(36, 5, HighlightRole.DEFINING),
                            CandidateHighlight(36, 8, HighlightRole.DEFINING),
                            CandidateHighlight(36, 9, HighlightRole.DEFINING),
                            CandidateHighlight(38, 4, HighlightRole.DEFINING),
                            CandidateHighlight(38, 8, HighlightRole.DEFINING),
                            CandidateHighlight(42, 4, HighlightRole.DEFINING),
                            CandidateHighlight(42, 5, HighlightRole.DEFINING),
                            CandidateHighlight(44, 8, HighlightRole.DEFINING),
                            CandidateHighlight(44, 9, HighlightRole.DEFINING),
                            CandidateHighlight(36, 3, HighlightRole.ELIMINATION),
                            CandidateHighlight(36, 7, HighlightRole.ELIMINATION),
                            CandidateHighlight(38, 1, HighlightRole.ELIMINATION),
                            CandidateHighlight(38, 7, HighlightRole.ELIMINATION),
                            CandidateHighlight(42, 3, HighlightRole.ELIMINATION),
                            CandidateHighlight(44, 7, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.HIDDEN_TRIPLE, SolutionType.NAKED_QUADRUPLE),
            keywords = listOf("hidden quad", "hidden quadruple", "hidden subset"),
        ),
        // ── Fish ─────────────────────────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.X_WING,
            theory =
                "An X-Wing is formed when a candidate digit appears in exactly two cells in each of two different " +
                    "rows, and those cells align on the same two columns (forming a rectangle). The digit must occupy " +
                    "two of the four corners, so it can be eliminated from all other cells in those two columns.\n\n" +
                    "The pattern also works transposed: two columns with matching pairs eliminate from two rows.",
            howToSpot =
                "• Filter candidates for a single digit.\n" +
                    "• Find two rows where that digit appears in exactly two positions.\n" +
                    "• If the column positions match, you have an X-Wing.\n" +
                    "• Eliminate the digit from other cells in those two columns.",
            example =
                BoardExample(
                    puzzle = ".1.54..6.5.698.4..8.4261.95.8.752634342816579765439....536.894.6.8194.5349.3.5.86",
                    candidateMasks =
                        intArrayOf(
                            258, 0, 320, 0, 0, 68, 198, 0, 194,
                            0, 70, 0, 0, 0, 68, 0, 3, 67,
                            0, 68, 0, 0, 0, 0, 68, 0, 0,
                            257, 0, 257, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 131, 3, 131,
                            3, 0, 0, 0, 66, 0, 0, 0, 67,
                            0, 66, 0, 0, 0, 0, 66, 0, 0,
                            0, 0, 65, 0, 66, 0, 67, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(19, 7, HighlightRole.DEFINING),
                            CandidateHighlight(24, 7, HighlightRole.DEFINING),
                            CandidateHighlight(64, 7, HighlightRole.DEFINING),
                            CandidateHighlight(69, 7, HighlightRole.DEFINING),
                            CandidateHighlight(10, 7, HighlightRole.ELIMINATION),
                            CandidateHighlight(6, 7, HighlightRole.ELIMINATION),
                            CandidateHighlight(78, 7, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SWORDFISH, SolutionType.JELLYFISH),
            keywords = listOf("x-wing", "fish", "basic fish", "two rows two columns"),
        ),
        StrategyEntry(
            type = SolutionType.SWORDFISH,
            theory =
                "A Swordfish extends the X-Wing concept to three rows and three columns. A candidate digit " +
                    "appears in 2–3 cells per row across exactly three rows, and all those cells fall in the same " +
                    "three columns. The digit is locked in those intersections and can be eliminated from other cells " +
                    "in the three columns.\n\n" +
                    "Not all nine intersection cells need to contain the candidate — the key is that each row's " +
                    "candidates are a subset of the three columns.",
            howToSpot =
                "• Filter for a single digit.\n" +
                    "• Find three rows where the digit appears in 2–3 cells each.\n" +
                    "• If all candidate positions fall within the same three columns, it's a Swordfish.\n" +
                    "• Eliminate the digit from other cells in those three columns.",
            example =
                BoardExample(
                    puzzle = "87362..5.1.25.3.784.5178.2373425.8.665..8.73228.36754.9167352843478.2.65528..63.7",
                    candidateMasks =
                        intArrayOf(
                            0, 0, 0, 0, 0, 264, 265, 0, 257,
                            0, 288, 0, 0, 264, 0, 296, 0, 0,
                            0, 288, 0, 0, 0, 0, 288, 0, 0,
                            0, 0, 0, 0, 0, 257, 0, 257, 0,
                            0, 0, 257, 264, 0, 265, 0, 0, 0,
                            0, 0, 257, 0, 0, 0, 0, 0, 257,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 257, 0, 257, 0, 0,
                            0, 0, 0, 264, 265, 0, 0, 257, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(10, 9, HighlightRole.DEFINING),
                            CandidateHighlight(13, 9, HighlightRole.DEFINING),
                            CandidateHighlight(15, 9, HighlightRole.DEFINING),
                            CandidateHighlight(19, 9, HighlightRole.DEFINING),
                            CandidateHighlight(24, 9, HighlightRole.DEFINING),
                            CandidateHighlight(67, 9, HighlightRole.DEFINING),
                            CandidateHighlight(69, 9, HighlightRole.DEFINING),
                            CandidateHighlight(76, 9, HighlightRole.ELIMINATION),
                            CandidateHighlight(6, 9, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.X_WING, SolutionType.JELLYFISH),
            keywords = listOf("swordfish", "fish", "three rows three columns"),
        ),
        StrategyEntry(
            type = SolutionType.JELLYFISH,
            theory =
                "A Jellyfish extends the fish concept to four rows and four columns. A candidate digit appears " +
                    "in 2–4 cells per row across exactly four rows, all falling within the same four columns.\n\n" +
                    "Jellyfish are rare in practice but follow the same logic as X-Wing and Swordfish. " +
                    "The digit is eliminated from other cells in the four cover columns.",
            howToSpot =
                "• Filter for a single digit.\n" +
                    "• Find four rows where the digit appears in 2–4 cells each.\n" +
                    "• If all positions fall within four columns, it's a Jellyfish.\n" +
                    "• Very rare — most puzzles can be solved without needing one.",
            example =
                BoardExample(
                    puzzle = "57.43.2..124..537.3..127.459.731.524.152.47392437596...915724.3452..31.773..41.52",
                    candidateMasks =
                        intArrayOf(
                            0, 0, 384, 0, 0, 160, 0, 385, 161,
                            0, 0, 0, 416, 416, 0, 0, 0, 160,
                            0, 160, 416, 0, 0, 0, 384, 0, 0,
                            0, 160, 0, 0, 0, 160, 0, 0, 0,
                            160, 0, 0, 0, 160, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 129, 129,
                            160, 0, 0, 0, 0, 0, 0, 160, 0,
                            0, 0, 0, 416, 416, 0, 0, 416, 0,
                            0, 0, 160, 416, 0, 0, 384, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(19, 8, HighlightRole.DEFINING),
                            CandidateHighlight(28, 8, HighlightRole.DEFINING),
                            CandidateHighlight(2, 8, HighlightRole.DEFINING),
                            CandidateHighlight(20, 8, HighlightRole.DEFINING),
                            CandidateHighlight(74, 8, HighlightRole.DEFINING),
                            CandidateHighlight(5, 8, HighlightRole.DEFINING),
                            CandidateHighlight(32, 8, HighlightRole.DEFINING),
                            CandidateHighlight(24, 8, HighlightRole.DEFINING),
                            CandidateHighlight(78, 8, HighlightRole.DEFINING),
                            CandidateHighlight(7, 8, HighlightRole.ELIMINATION),
                            CandidateHighlight(8, 8, HighlightRole.ELIMINATION),
                            CandidateHighlight(75, 8, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SWORDFISH, SolutionType.X_WING),
            keywords = listOf("jellyfish", "fish", "four rows four columns"),
        ),
        // ── Single-Digit Patterns ──────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.SKYSCRAPER,
            theory =
                "A Skyscraper is a single-digit pattern built from two conjugate pairs (strong links) that share " +
                    "one endpoint's row or column. It looks like two 'towers' of equal height connected at their bases.\n\n" +
                    "If a digit has exactly two positions in each of two rows (or columns), and one position from each " +
                    "row aligns in the same column, then cells that see both 'top' positions can have the digit eliminated.",
            howToSpot =
                "• Filter for a single digit and find rows/columns with exactly two candidates.\n" +
                    "• Look for two such rows sharing a column position (the 'base').\n" +
                    "• Cells seeing both non-base endpoints can be eliminated.",
            example =
                BoardExample(
                    puzzle = "172...3.99..173....349.287142.79618.7..8219.489153472624.3.9517..9.17...317...69.",
                    candidateMasks =
                        intArrayOf(
                            0, 0, 0, 40, 184, 144, 0, 48, 0,
                            0, 176, 176, 0, 0, 0, 10, 56, 18,
                            48, 0, 0, 0, 48, 0, 0, 0, 0,
                            0, 0, 20, 0, 0, 0, 0, 0, 20,
                            0, 48, 52, 0, 0, 0, 0, 20, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 160, 0, 160, 0, 0, 0, 0,
                            48, 176, 0, 34, 0, 0, 10, 12, 134,
                            0, 0, 0, 10, 152, 144, 0, 0, 130
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(18, 6, HighlightRole.DEFINING),
                            CandidateHighlight(22, 6, HighlightRole.SECONDARY),
                            CandidateHighlight(58, 6, HighlightRole.SECONDARY),
                            CandidateHighlight(56, 6, HighlightRole.DEFINING),
                            CandidateHighlight(11, 6, HighlightRole.ELIMINATION),
                            CandidateHighlight(63, 6, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.TWO_STRING_KITE, SolutionType.TURBOT_FISH),
            keywords = listOf("skyscraper", "single digit", "turbot", "conjugate pair"),
        ),
        StrategyEntry(
            type = SolutionType.TWO_STRING_KITE,
            theory =
                "A 2-String Kite uses a box as a bridge between a row strong link and a column strong link for the same digit. " +
                    "One endpoint from the row link and one from the column link are in the same box, connecting them.\n\n" +
                    "The two 'free' endpoints (outside the box) form the elimination zone: any cell seeing both can lose the digit.",
            howToSpot =
                "• Filter for one digit. Find a row with exactly two positions and a column with exactly two.\n" +
                    "• Check if one cell from each shares a box.\n" +
                    "• The other two cells are the 'kite tips' — eliminate from cells seeing both.",
            example =
                BoardExample(
                    puzzle = ".76985.435..34....4.32.1.5..6253..1435149.7...4...253...56.34..63..54..8..48.9365",
                    candidateMasks =
                        intArrayOf(
                            3, 0, 0, 0, 0, 0, 3, 0, 0,
                            0, 3, 384, 0, 0, 96, 419, 450, 323,
                            0, 384, 0, 0, 96, 0, 416, 0, 320,
                            320, 0, 0, 0, 0, 192, 384, 0, 0,
                            0, 0, 0, 0, 0, 160, 0, 130, 34,
                            384, 0, 448, 65, 33, 0, 0, 0, 288,
                            387, 384, 0, 0, 3, 0, 0, 320, 321,
                            0, 0, 320, 65, 0, 0, 259, 258, 0,
                            67, 3, 0, 0, 67, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(0, 1, HighlightRole.DEFINING),
                            CandidateHighlight(6, 1, HighlightRole.SECONDARY),
                            CandidateHighlight(17, 1, HighlightRole.SECONDARY),
                            CandidateHighlight(62, 1, HighlightRole.DEFINING),
                            CandidateHighlight(54, 1, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SKYSCRAPER, SolutionType.EMPTY_RECTANGLE),
            keywords = listOf("kite", "2-string kite", "single digit"),
        ),
        StrategyEntry(
            type = SolutionType.EMPTY_RECTANGLE,
            theory =
                "An Empty Rectangle uses a box where a candidate digit is confined to one row and one column within the box " +
                    "(forming an 'L' or cross shape), combined with a strong link in another row or column.\n\n" +
                    "The box's 'empty rectangle' guarantees the digit is in one of the intersection cells, which " +
                    "connects to the strong link to force an elimination.",
            howToSpot =
                "• Filter for one digit. Find a box where the digit's candidates form a cross/L shape.\n" +
                    "• Find a strong link (conjugate pair) in a row or column that intersects the box's arm.\n" +
                    "• The other endpoint of the strong link sees the box's other arm for elimination.",
            example =
                BoardExample(
                    puzzle = "5...3...21.26.984...6..2.9.2.19.5...6...2...1...4.12.9.6.2..91.41389752692..16..4",
                    candidateMasks =
                        intArrayOf(
                            0, 392, 264, 65, 0, 136, 97, 96, 0,
                            0, 68, 0, 0, 80, 0, 0, 0, 84,
                            196, 204, 0, 81, 136, 0, 69, 0, 84,
                            0, 204, 0, 0, 224, 0, 108, 228, 196,
                            0, 472, 264, 68, 0, 132, 72, 208, 0,
                            196, 212, 192, 0, 224, 0, 0, 244, 0,
                            192, 0, 208, 0, 24, 12, 0, 0, 196,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 208, 20, 0, 0, 68, 196, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(6, 1, HighlightRole.DEFINING),
                            CandidateHighlight(24, 1, HighlightRole.DEFINING),
                            CandidateHighlight(3, 1, HighlightRole.SECONDARY),
                            CandidateHighlight(21, 1, HighlightRole.SECONDARY),
                            CandidateHighlight(21, 1, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SKYSCRAPER, SolutionType.TWO_STRING_KITE),
            keywords = listOf("empty rectangle", "ER", "single digit", "box cross"),
        ),
        StrategyEntry(
            type = SolutionType.TURBOT_FISH,
            theory =
                "The Turbot Fish (or Turbot Crane) is a generalized single-digit chain of length 4. " +
                    "It uses two strong links connected by a weak link to create an elimination.\n\n" +
                    "Skyscrapers, 2-String Kites, and Empty Rectangles are all specific geometric arrangements " +
                    "of the Turbot Fish pattern. The general case links any two conjugate pairs via a weak inference.",
            howToSpot =
                "• Filter for one digit.\n" +
                    "• Find two strong links (conjugate pairs) for that digit.\n" +
                    "• If an endpoint of one pair sees an endpoint of the other pair (weak link), " +
                    "the remaining two endpoints form the elimination zone.",
            example =
                BoardExample(
                    puzzle = "1.5.7296393.6.5.72726..35..25..64.97.7.1296.569.5.72....2..6751367251..9519748326",
                    candidateMasks =
                        intArrayOf(
                            0, 136, 0, 136, 0, 0, 0, 0, 0,
                            0, 0, 136, 0, 129, 0, 137, 0, 0,
                            0, 0, 0, 392, 385, 0, 0, 137, 136,
                            0, 0, 133, 132, 0, 0, 129, 0, 0,
                            136, 0, 140, 0, 0, 0, 0, 140, 0,
                            0, 0, 141, 0, 132, 0, 0, 141, 136,
                            136, 136, 0, 260, 260, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 136, 136, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(26, 8, HighlightRole.DEFINING),
                            CandidateHighlight(53, 8, HighlightRole.SECONDARY),
                            CandidateHighlight(49, 8, HighlightRole.SECONDARY),
                            CandidateHighlight(30, 8, HighlightRole.DEFINING),
                            CandidateHighlight(21, 8, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SKYSCRAPER, SolutionType.TWO_STRING_KITE, SolutionType.EMPTY_RECTANGLE),
            keywords = listOf("turbot fish", "turbot crane", "single digit chain"),
        ),
        // ── Wings ────────────────────────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.XY_WING,
            theory =
                "An XY-Wing consists of three bivalue cells: a pivot with candidates {X,Y} and two pincers, " +
                    "one with {X,Z} and one with {Y,Z}. The pivot sees both pincers. If the pivot is X, the {Y,Z} " +
                    "pincer becomes Z. If the pivot is Y, the {X,Z} pincer becomes Z. Either way, Z is true in one pincer.\n\n" +
                    "Any cell that sees both pincers can have Z eliminated, since Z must be in at least one of them.",
            howToSpot =
                "• Look for a bivalue cell (the pivot) that sees two other bivalue cells.\n" +
                    "• The pivot shares one digit with each pincer, and the pincers share a third digit Z.\n" +
                    "• Eliminate Z from cells seeing both pincers.",
            example =
                BoardExample(
                    puzzle = "6748..9...32.4967.9....6..4...4...9649..6..8..26.984.73..6.4..9.459..36..69..3741",
                    candidateMasks =
                        intArrayOf(
                            0, 0, 0, 0, 23, 19, 0, 23, 22,
                            145, 0, 0, 17, 0, 0, 0, 0, 144,
                            0, 145, 129, 87, 87, 0, 147, 23, 0,
                            81, 145, 197, 0, 23, 83, 19, 0, 0,
                            0, 0, 69, 83, 0, 83, 19, 0, 22,
                            17, 0, 0, 21, 0, 0, 0, 21, 0,
                            0, 129, 193, 0, 67, 0, 146, 18, 0,
                            195, 0, 0, 0, 195, 67, 0, 0, 130,
                            130, 0, 0, 18, 146, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(71, 2, HighlightRole.SECONDARY),
                            CandidateHighlight(71, 8, HighlightRole.SECONDARY),
                            CandidateHighlight(61, 2, HighlightRole.DEFINING),
                            CandidateHighlight(61, 5, HighlightRole.DEFINING),
                            CandidateHighlight(17, 5, HighlightRole.DEFINING),
                            CandidateHighlight(17, 8, HighlightRole.DEFINING),
                            CandidateHighlight(7, 5, HighlightRole.ELIMINATION),
                            CandidateHighlight(25, 5, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.XYZ_WING, SolutionType.W_WING),
            keywords = listOf("xy-wing", "y-wing", "pivot", "pincer", "bivalue"),
        ),
        StrategyEntry(
            type = SolutionType.XYZ_WING,
            theory =
                "An XYZ-Wing extends the XY-Wing by allowing the pivot to have three candidates {X,Y,Z}. " +
                    "One pincer has {X,Z} and the other has {Y,Z}. The same logic applies: no matter what the pivot " +
                    "becomes, Z ends up in at least one pincer.\n\n" +
                    "The elimination is more restricted: only cells seeing the pivot AND both pincers can lose Z, " +
                    "since the pivot itself contains Z.",
            howToSpot =
                "• Find a cell with three candidates that sees two bivalue cells.\n" +
                    "• The pivot's three digits must be distributed: one shared with each pincer, Z in all three.\n" +
                    "• Eliminate Z from cells seeing all three cells (pivot + both pincers).",
            example =
                BoardExample(
                    puzzle = "..38..9..8...69.3.9..3...853..9..8..187.325.9..9..8..3298..735.73.28..916.1.93728",
                    candidateMasks =
                        intArrayOf(
                            24, 107, 0, 0, 91, 25, 0, 105, 106,
                            0, 91, 10, 89, 0, 0, 11, 0, 74,
                            0, 107, 42, 0, 75, 9, 43, 0, 0,
                            0, 42, 58, 0, 89, 57, 0, 105, 74,
                            0, 0, 0, 40, 0, 0, 0, 40, 0,
                            24, 42, 0, 105, 89, 0, 43, 105, 0,
                            0, 0, 0, 41, 9, 0, 0, 0, 40,
                            0, 0, 24, 0, 0, 56, 40, 0, 0,
                            0, 24, 0, 24, 0, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(5, 1, HighlightRole.SECONDARY),
                            CandidateHighlight(5, 4, HighlightRole.SECONDARY),
                            CandidateHighlight(5, 5, HighlightRole.SECONDARY),
                            CandidateHighlight(0, 4, HighlightRole.DEFINING),
                            CandidateHighlight(0, 5, HighlightRole.DEFINING),
                            CandidateHighlight(23, 1, HighlightRole.DEFINING),
                            CandidateHighlight(23, 4, HighlightRole.DEFINING),
                            CandidateHighlight(4, 4, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.XY_WING, SolutionType.W_WING),
            keywords = listOf("xyz-wing", "pivot", "three candidates"),
        ),
        StrategyEntry(
            type = SolutionType.W_WING,
            theory =
                "A W-Wing consists of two bivalue cells with the same pair {X,Z} connected by a strong link on X. " +
                    "If cell A is Z then cell B must also contain Z (since X is forced through the chain). " +
                    "If cell A is X, then through the strong link, X propagates, and cell B becomes Z.\n\n" +
                    "Either way, at least one of them is Z, so any cell seeing both can have Z eliminated.",
            howToSpot =
                "• Find two bivalue cells with identical candidates {X,Z}.\n" +
                    "• Check if there's a strong link on digit X that connects a peer of cell A to a peer of cell B.\n" +
                    "• Eliminate Z from cells seeing both bivalue cells.",
            example =
                BoardExample(
                    puzzle = "8975..3..3...79.85.5.83.7.954396.87.679.485.31827539469.5.87.3.71.39..58.38..5697",
                    candidateMasks =
                        intArrayOf(
                            0, 0, 0, 0, 3, 42, 0, 33, 10,
                            0, 34, 9, 34, 0, 0, 9, 0, 0,
                            10, 0, 33, 0, 0, 41, 0, 34, 0,
                            0, 0, 0, 0, 0, 3, 0, 0, 3,
                            0, 0, 0, 3, 0, 0, 0, 3, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 34, 0, 42, 0, 0, 3, 0, 9,
                            0, 0, 40, 0, 0, 34, 10, 0, 0,
                            10, 0, 0, 9, 3, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(4, 1, HighlightRole.DEFINING),
                            CandidateHighlight(4, 2, HighlightRole.DEFINING),
                            CandidateHighlight(32, 1, HighlightRole.DEFINING),
                            CandidateHighlight(32, 2, HighlightRole.DEFINING),
                            CandidateHighlight(8, 2, HighlightRole.SECONDARY),
                            CandidateHighlight(35, 2, HighlightRole.SECONDARY),
                            CandidateHighlight(23, 1, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.XY_WING, SolutionType.REMOTE_PAIR),
            keywords = listOf("w-wing", "bivalue", "strong link"),
        ),
        StrategyEntry(
            type = SolutionType.REMOTE_PAIR,
            theory =
                "A Remote Pair is a chain of bivalue cells all containing the same two candidates {X,Y}, " +
                    "connected through shared units. When the chain has an even number of cells, " +
                    "the two endpoints must contain different digits. Any cell seeing both endpoints can have " +
                    "both X and Y eliminated.\n\n" +
                    "Think of it as alternating colours along the chain: each link flips which digit is chosen.",
            howToSpot =
                "• Find bivalue cells with the same pair, forming a chain through shared rows/cols/boxes.\n" +
                    "• Count the chain length. If even (4, 6, ...), the endpoints differ.\n" +
                    "• Eliminate both digits from cells seeing both chain endpoints.",
            example =
                BoardExample(
                    puzzle =
                        "000105000" +
                            "105926437" +
                            "926437105" +
                            "214350769" +
                            "350769214" +
                            "769214350" +
                            "431572096" +
                            "572096431" +
                            "096431572",
                    candidateMasks =
                        fullBoard(
                            "000105000" +
                                "105926437" +
                                "926437105" +
                                "214350769" +
                                "350769214" +
                                "769214350" +
                                "431572096" +
                                "572096431" +
                                "096431572",
                            mapOf(
                                cell(0, 0) to mask(3, 8),
                                cell(0, 1) to mask(4, 7, 8),
                                cell(0, 2) to mask(4, 7, 8),
                                cell(0, 4) to mask(3, 8),
                                cell(0, 5) to mask(6, 8),
                                cell(0, 6) to mask(2, 6, 8),
                                cell(0, 7) to mask(2, 6, 8),
                                cell(0, 8) to mask(2, 6),
                                cell(3, 3) to mask(8),
                                cell(6, 6) to mask(8),
                            ),
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(cell(0, 0), 3, COLOR_A),
                            CandidateHighlight(cell(0, 0), 8, COLOR_B),
                            CandidateHighlight(cell(0, 4), 3, COLOR_B),
                            CandidateHighlight(cell(0, 4), 8, COLOR_A),
                            CandidateHighlight(cell(0, 1), 8, ELIMINATION),
                            CandidateHighlight(cell(0, 2), 8, ELIMINATION),
                            CandidateHighlight(cell(0, 5), 8, ELIMINATION),
                            CandidateHighlight(cell(0, 6), 8, ELIMINATION),
                            CandidateHighlight(cell(0, 7), 8, ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.W_WING, SolutionType.XY_WING, SolutionType.SIMPLE_COLORS_TRAP),
            keywords = listOf("remote pair", "bivalue chain", "alternating"),
        ),
        // ── Coloring ─────────────────────────────────────────────────────────────
        StrategyEntry(
            type = SolutionType.SIMPLE_COLORS_TRAP,
            theory =
                "Simple Coloring (Trap) assigns two colours to a single-digit strong-link network. " +
                    "Start from any conjugate pair and alternate colours along strong links (if the digit is in " +
                    "cell A (green) of a conjugate pair, it's not in cell B (purple), and vice versa).\n\n" +
                    "If a non-coloured cell sees cells of BOTH colours, the digit can be eliminated from that cell — " +
                    "one colour must be true, and either way that cell can't have the digit. This is the 'trap' rule.",
            howToSpot =
                "• Filter for one digit. Build the conjugate-pair network.\n" +
                    "• Colour alternating cells green and purple.\n" +
                    "• Any uncoloured cell seeing both a green and a purple cell loses the digit.",
            example =
                BoardExample(
                    puzzle = "6.4..5712.1.4.....5....1..8.6.178...3..259..6...643...97.5....3.....6.9.8.69..2..",
                    candidateMasks =
                        intArrayOf(
                            0, 388, 0, 132, 388, 0, 0, 0, 0,
                            66, 0, 388, 0, 420, 66, 308, 52, 272,
                            0, 262, 326, 68, 294, 0, 300, 44, 0,
                            10, 0, 274, 0, 0, 0, 284, 30, 280,
                            0, 136, 193, 0, 0, 0, 137, 200, 0,
                            67, 402, 467, 0, 0, 0, 401, 210, 337,
                            0, 0, 3, 0, 131, 10, 169, 168, 0,
                            11, 30, 23, 196, 135, 0, 152, 0, 89,
                            0, 28, 0, 0, 5, 72, 0, 88, 89
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(9, 7, HighlightRole.COLOR_A),
                            CandidateHighlight(77, 7, HighlightRole.COLOR_A),
                            CandidateHighlight(21, 7, HighlightRole.COLOR_A),
                            CandidateHighlight(71, 7, HighlightRole.COLOR_A),
                            CandidateHighlight(14, 7, HighlightRole.COLOR_B),
                            CandidateHighlight(45, 7, HighlightRole.COLOR_B),
                            CandidateHighlight(20, 7, HighlightRole.COLOR_B),
                            CandidateHighlight(66, 7, HighlightRole.COLOR_B),
                            CandidateHighlight(53, 7, HighlightRole.ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SIMPLE_COLORS_WRAP, SolutionType.MULTI_COLORS_1),
            keywords = listOf("coloring", "trap", "conjugate", "strong link", "colour"),
        ),
        StrategyEntry(
            type = SolutionType.SIMPLE_COLORS_WRAP,
            theory =
                "Simple Coloring (Wrap) uses the same two-colour network as the Trap rule, but detects a contradiction. " +
                    "If two cells of the SAME colour see each other, that colour is impossible — so the opposite colour " +
                    "must be the true one.\n\n" +
                    "When a wrap is found, ALL cells of the contradicted colour can have the digit eliminated, " +
                    "and all cells of the surviving colour are set to that digit.",
            howToSpot =
                "• Build the single-digit coloring network.\n" +
                    "• Check if any two same-colour cells share a unit (row/col/box).\n" +
                    "• If so, that colour is false: eliminate the digit from ALL cells of that colour.",
            example =
                BoardExample(
                    puzzle = "7129..4854938571628562417392.549.817174.8259..8971524.9.1574.28548.29.71.271.8954",
                    candidateMasks =
                        intArrayOf(
                            0, 0, 0, 0, 36, 36, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 36, 0, 0, 0, 36, 0, 0, 0,
                            0, 0, 0, 36, 0, 0, 0, 0, 36,
                            36, 0, 0, 0, 0, 0, 0, 0, 36,
                            0, 36, 0, 0, 0, 0, 36, 0, 0,
                            0, 0, 0, 36, 0, 0, 36, 0, 0,
                            36, 0, 0, 0, 36, 0, 0, 0, 0
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(5, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(76, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(28, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(39, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(45, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(55, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(69, 3, HighlightRole.COLOR_A),
                            CandidateHighlight(4, 3, HighlightRole.COLOR_B),
                            CandidateHighlight(32, 3, HighlightRole.COLOR_B),
                            CandidateHighlight(72, 3, HighlightRole.COLOR_B),
                            CandidateHighlight(66, 3, HighlightRole.COLOR_B),
                            CandidateHighlight(44, 3, HighlightRole.COLOR_B),
                            CandidateHighlight(53, 3, HighlightRole.COLOR_B),
                            CandidateHighlight(60, 3, HighlightRole.COLOR_B),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SIMPLE_COLORS_TRAP, SolutionType.MULTI_COLORS_1),
            keywords = listOf("coloring", "wrap", "contradiction", "colour"),
        ),
        StrategyEntry(
            type = SolutionType.MULTI_COLORS_1,
            theory =
                "Multi-Coloring Type 1 extends Simple Coloring by linking two separate coloring clusters. " +
                    "If a colour from cluster 1 sees a colour from cluster 2, one of those colours must be false. " +
                    "This 'bridges' the clusters, allowing eliminations in the combined network.\n\n" +
                    "Type 1 handles the case where a colour in one cluster directly contradicts a colour in another.",
            howToSpot =
                "• Build coloring clusters for a single digit (separate connected components).\n" +
                    "• Check inter-cluster visibility between opposite colours.\n" +
                    "• When colours from different clusters conflict, merge the information for elimination.",
            example =
                BoardExample(
                    puzzle =
                        "917438265" +
                            "438265917" +
                            "265917438" +
                            "000143000" +
                            "143000002" +
                            "002000143" +
                            "324806571" +
                            "806571324" +
                            "571324806",
                    candidateMasks =
                        fullBoard(
                            "917438265" +
                                "438265917" +
                                "265917438" +
                                "000143000" +
                                "143000002" +
                                "002000143" +
                                "324806571" +
                                "806571324" +
                                "571324806",
                            mapOf(
                                cell(3, 0) to mask(6, 8),
                                cell(3, 1) to mask(5, 6, 8),
                                cell(3, 2) to mask(6, 8, 9),
                                cell(3, 6) to mask(6, 7, 8, 9),
                                cell(3, 7) to mask(7, 8),
                                cell(3, 8) to mask(6, 8, 9),
                                cell(4, 3) to mask(5, 6, 7, 8, 9),
                                cell(4, 4) to mask(5, 6, 7, 8, 9),
                                cell(4, 5) to mask(5, 6, 7, 8, 9),
                                cell(5, 0) to mask(6, 8, 9),
                                cell(5, 1) to mask(5, 6, 7, 8, 9),
                                cell(5, 2) to mask(6, 8, 9),
                                cell(5, 3) to mask(5, 6, 7, 8, 9),
                                cell(5, 4) to mask(5, 6, 7, 8, 9),
                                cell(5, 5) to mask(5, 6, 7, 8, 9),
                            ),
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(cell(3, 2), 9, COLOR_A),
                            CandidateHighlight(cell(3, 8), 9, COLOR_B),
                            CandidateHighlight(cell(5, 0), 9, COLOR_A),
                            CandidateHighlight(cell(5, 2), 9, COLOR_B),
                            CandidateHighlight(cell(4, 3), 9, COLOR_A),
                            CandidateHighlight(cell(4, 5), 9, COLOR_B),
                            CandidateHighlight(cell(5, 3), 9, ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.SIMPLE_COLORS_TRAP, SolutionType.MULTI_COLORS_2),
            keywords = listOf("multi-coloring", "multi colors", "cluster bridge"),
        ),
        StrategyEntry(
            type = SolutionType.MULTI_COLORS_2,
            theory =
                "Multi-Coloring Type 2 handles a different inter-cluster interaction. When a colour from one cluster " +
                    "sees both colours of another cluster, that first colour must be false (since one of the second " +
                    "cluster's colours must be true).\n\n" +
                    "This eliminates the digit from all cells of the contradicted colour in the first cluster.",
            howToSpot =
                "• Build separate coloring clusters for a digit.\n" +
                    "• Check if a colour in cluster A sees both colours of cluster B.\n" +
                    "• If so, that colour in A is false — eliminate the digit from all its cells.",
            example =
                BoardExample(
                    puzzle =
                        "829415736" +
                            "415736829" +
                            "736829415" +
                            "000143000" +
                            "143000000" +
                            "000000143" +
                            "361278594" +
                            "278594361" +
                            "594361278",
                    candidateMasks =
                        fullBoard(
                            "829415736" +
                                "415736829" +
                                "736829415" +
                                "000143000" +
                                "143000000" +
                                "000000143" +
                                "361278594" +
                                "278594361" +
                                "594361278",
                            mapOf(
                                cell(3, 0) to mask(5, 6, 7),
                                cell(3, 1) to mask(5, 6, 7, 8),
                                cell(3, 2) to mask(2, 6, 8),
                                cell(3, 6) to mask(2, 5, 6, 7, 8, 9),
                                cell(3, 7) to mask(2, 5, 6, 7, 8, 9),
                                cell(3, 8) to mask(2, 5, 6, 7, 8, 9),
                                cell(4, 3) to mask(2, 5, 6, 7, 8, 9),
                                cell(4, 4) to mask(2, 5, 6, 7, 8, 9),
                                cell(4, 5) to mask(2, 5, 6, 7, 8, 9),
                                cell(4, 6) to mask(2, 5, 6, 7, 8),
                                cell(4, 7) to mask(2, 5, 6, 7, 8),
                                cell(4, 8) to mask(2, 5, 6, 7, 8),
                                cell(5, 0) to mask(5, 6, 7),
                                cell(5, 1) to mask(2, 5, 6, 7, 8, 9),
                                cell(5, 2) to mask(2, 6, 8, 9),
                                cell(5, 3) to mask(2, 5, 6, 7, 8, 9),
                                cell(5, 4) to mask(2, 5, 6, 7, 8, 9),
                                cell(5, 5) to mask(2, 5, 6, 7, 8, 9),
                            ),
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(cell(3, 0), 5, COLOR_A),
                            CandidateHighlight(cell(3, 1), 5, COLOR_B),
                            CandidateHighlight(cell(5, 0), 5, COLOR_B),
                            CandidateHighlight(cell(5, 1), 5, COLOR_A),
                            CandidateHighlight(cell(4, 3), 5, COLOR_A),
                            CandidateHighlight(cell(4, 6), 5, COLOR_B),
                            CandidateHighlight(cell(3, 0), 5, ELIMINATION),
                            CandidateHighlight(cell(5, 1), 5, ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.MULTI_COLORS_1, SolutionType.SIMPLE_COLORS_TRAP),
            keywords = listOf("multi-coloring", "multi colors type 2", "cluster"),
        ),
        // ── Chains (hand-crafted — no solvers) ────────────────────────────────
        StrategyEntry(
            type = SolutionType.X_CHAIN,
            theory =
                "An X-Chain is a single-digit chain of alternating strong and weak links. Starting from a strong link, " +
                    "the chain proceeds: strong → weak → strong → weak → ... → strong. Because the chain starts and " +
                    "ends with strong links, both endpoints can't be false simultaneously.\n\n" +
                    "Any cell that sees both endpoints can have the digit eliminated.",
            howToSpot =
                "• Filter for one digit. Build the conjugate-pair (strong link) network.\n" +
                    "• Find chains that alternate strong-weak links and have an odd number of links.\n" +
                    "• The endpoints are guaranteed: at least one is true.\n" +
                    "• Eliminate from cells seeing both endpoints.",
            example =
                BoardExample(
                    puzzle =
                        "900000503" +
                            "645397218" +
                            "318254679" +
                            "870000456" +
                            "456138792" +
                            "231769840" +
                            "790000364" +
                            "560000920" +
                            "184923507",
                    candidateMasks =
                        fullBoard(
                            "900000503" +
                                "645397218" +
                                "318254679" +
                                "870000456" +
                                "456138792" +
                                "231769840" +
                                "790000364" +
                                "560000920" +
                                "184923507",
                            mapOf(
                                cell(0, 0) to mask(2),
                                cell(0, 1) to mask(2, 7),
                                cell(0, 2) to mask(7),
                                cell(0, 3) to mask(1, 4, 6, 8),
                                cell(0, 4) to mask(1, 4, 6, 8),
                                cell(0, 5) to mask(1, 4, 6, 8),
                                cell(0, 8) to mask(1),
                                cell(3, 3) to mask(2, 9),
                                cell(3, 4) to mask(2, 9),
                                cell(3, 5) to mask(1, 2, 9),
                                cell(5, 8) to mask(5),
                                cell(6, 3) to mask(1, 2, 5, 8),
                                cell(6, 4) to mask(1, 2, 5, 8),
                                cell(6, 5) to mask(1, 2, 5, 8),
                                cell(7, 0) to mask(3),
                                cell(7, 3) to mask(1, 4, 7, 8),
                                cell(7, 4) to mask(1, 4, 7, 8),
                                cell(7, 5) to mask(1, 4, 7, 8),
                                cell(7, 7) to mask(1, 7, 8),
                                cell(7, 8) to mask(1, 7, 8),
                                cell(8, 6) to mask(6),
                                cell(8, 8) to mask(6),
                                cell(0, 6) to mask(2),
                                cell(3, 6) to mask(1, 2),
                                cell(3, 2) to mask(2, 9),
                                cell(7, 2) to mask(2, 7),
                            ),
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(cell(0, 1), 2, DEFINING),
                            CandidateHighlight(cell(0, 6), 2, SECONDARY),
                            CandidateHighlight(cell(3, 6), 2, SECONDARY),
                            CandidateHighlight(cell(3, 2), 2, SECONDARY),
                            CandidateHighlight(cell(7, 2), 2, SECONDARY),
                            CandidateHighlight(cell(7, 8), 2, DEFINING),
                        ),
                ),
            relatedTypes = listOf(SolutionType.XY_CHAIN, SolutionType.SIMPLE_COLORS_TRAP),
            keywords = listOf("x-chain", "single digit chain", "alternating inference"),
        ),
        StrategyEntry(
            type = SolutionType.XY_CHAIN,
            theory =
                "An XY-Chain is a chain of bivalue cells where each consecutive pair shares a digit through a " +
                    "common unit (weak link), and within each cell the two candidates form a strong link. " +
                    "The chain alternates: one digit is 'on' at each end.\n\n" +
                    "If the chain starts with digit X at cell A and ends with digit X at cell B, then at least one " +
                    "endpoint has X, so cells seeing both A and B can have X eliminated.",
            howToSpot =
                "• Find sequences of bivalue cells connected through shared units.\n" +
                    "• Each cell's internal strong link alternates truth values along the chain.\n" +
                    "• Matching digits at both endpoints allow elimination from cells seeing both.",
            example =
                BoardExample(
                    puzzle =
                        "000836002" +
                            "836002000" +
                            "002000836" +
                            "000648200" +
                            "648200003" +
                            "203003648" +
                            "064382510" +
                            "382510064" +
                            "510064382",
                    candidateMasks =
                        fullBoard(
                            "000836002" +
                                "836002000" +
                                "002000836" +
                                "000648200" +
                                "648200003" +
                                "203003648" +
                                "064382510" +
                                "382510064" +
                                "510064382",
                            mapOf(
                                cell(0, 0) to mask(1, 4),
                                cell(0, 1) to mask(5, 7, 9),
                                cell(0, 2) to mask(5, 7, 9),
                                cell(0, 5) to mask(4, 7),
                                cell(0, 7) to mask(5, 9),
                                cell(0, 8) to mask(5, 9),
                                cell(1, 3) to mask(1, 4, 5, 7, 9),
                                cell(1, 4) to mask(1, 4, 5, 7, 9),
                                cell(1, 6) to mask(1, 5, 7, 9),
                                cell(1, 7) to mask(1, 5, 7, 9),
                                cell(1, 8) to mask(1, 5, 7, 9),
                                cell(2, 3) to mask(1, 4, 5, 7, 9),
                                cell(2, 4) to mask(1, 4, 5, 7, 9),
                                cell(2, 5) to mask(1, 4, 5, 7, 9),
                                cell(3, 0) to mask(1, 5, 7, 9),
                                cell(3, 1) to mask(1, 5, 7, 9),
                                cell(3, 2) to mask(1, 5, 7, 9),
                                cell(3, 5) to mask(2, 7),
                                cell(3, 7) to mask(3, 5, 7, 9),
                                cell(3, 8) to mask(1, 2),
                                cell(4, 3) to mask(5, 7, 9),
                                cell(4, 4) to mask(1, 5, 7, 9),
                                cell(4, 8) to mask(1, 5, 7, 9),
                                cell(5, 0) to mask(5, 7, 9),
                                cell(5, 2) to mask(5, 7, 9),
                                cell(5, 3) to mask(1, 5, 7, 9),
                            ),
                        ),
                    highlights =
                        listOf(
                            CandidateHighlight(cell(0, 0), 1, DEFINING),
                            CandidateHighlight(cell(0, 0), 4, SECONDARY),
                            CandidateHighlight(cell(0, 5), 4, SECONDARY),
                            CandidateHighlight(cell(0, 5), 7, SECONDARY),
                            CandidateHighlight(cell(3, 5), 7, SECONDARY),
                            CandidateHighlight(cell(3, 5), 2, SECONDARY),
                            CandidateHighlight(cell(3, 8), 2, SECONDARY),
                            CandidateHighlight(cell(3, 8), 1, DEFINING),
                            CandidateHighlight(cell(3, 0), 1, ELIMINATION),
                            CandidateHighlight(cell(3, 1), 1, ELIMINATION),
                            CandidateHighlight(cell(3, 2), 1, ELIMINATION),
                        ),
                ),
            relatedTypes = listOf(SolutionType.X_CHAIN, SolutionType.XY_WING),
            keywords = listOf("xy-chain", "bivalue chain", "alternating inference"),
        ),
    )
